### PR TITLE
Update Polish Translation

### PR DESCRIPTION
**Pull request by Gootector**
Update Polish Translation

Greetings,
Gootector

### CODE REVIEW

**Comment by Gootector** [comment]
Wwork in progress...

**Comment by Gootector** [comment]
Work in progress...

**Comment by helge17** [comment]
Thank you, just let me know when you are finished. Maybe it would be possible to summarize the changes in one commit, because this creates a lot of entries in the commit history.

**Comment by Gootector** [comment]
> Thank you, just let me know when you are finished. Maybe it would be possible to summarize the changes in one commit, because this creates a lot of entries in the commit history.

OK. Now, I squashed all commits. When I finish this, I'll let you know.

**Comment by Gootector** [comment]
@helge17 OK. At this moment - done; with the latest strings.

Greetings,
Gootector

**Comment by Gootector** [comment]
@helge17 Could you merge?

**Comment by guiv42** [comment]
@Gootector : thanks for the translation! Next time I suggest you mark the Pull Request as "draft" until you are finished, so we know when it's ready to be merged

@helge17 : logically you should see an option to "merge squash" Pull Requests (drop-down list in "merge" button ? I don't remember), so it creates one single commit in master

**Comment by Gootector** [comment]
@guiv42 My PR contains the latest strings. It's OK.

**Comment by Gootector** [comment]
Thanks!

**Pull request merged**
