### PR TITLE
Perf optimization, update SWT for Linux to 4.26

### PR DESCRIPTION
**Pull request by guiv42**
See #403 

@helge17 , I would appreciate your feedback before merging this PR, especially:
- not tested on macOS
- ~~not tested on FreeBSD (I've got some issues in my VM, need to spend some time on it)~~ I could finally test on FreeBSD, it's OK. Better apply the same optimization as for Linux, as it uses the same gtk flavour of SWT
- I reverted 429c42f159f4e07a3c6dded9dabc363be2478a7f: it modified `build_tuxguitar_from_source.sh` (untested)

on macOS and Windows, behavior should be unchanged.
on Linux and FreeBSD, the only visible modification is that scrollbars are now hidden when playing.
no impact on Android.

I think we shall try to update SWT for Linux quite soon, to leave us some time to detect possible issues. Now, if someone wants to package 1.6.3 for debian 12, performance issue #403 will be present.

### CODE REVIEW

**Comment by helge17** [comment]
The patch works good on all OS, I did not notice any negative side effects.

> side effect on Windows, sometimes one scrollbar is not displayed correctly when player stops

With view.hide-scrollbars-when-playing=true under Windows, the vertical scrollbar is not displayed again if the cursor jumps down one line. If you stop playback in the same line, the scrollbar is displayed.

**Review by helge17 — COMMENTED** [review]
The patch works good on all OS, I did not notice any negative side effects.

> side effect on Windows, sometimes one scrollbar is not displayed correctly when player stops

With view.hide-scrollbars-when-playing=true under Windows, the vertical scrollbar is not displayed again if the cursor jumps down one line. If you stop playback in the same line, the scrollbar is displayed.

**Comment by guiv42** [comment]
Thanks @helge17 for the test. I'll have one more try, with the objective to fix the issue on Windows, so we keep a similar behavior with all operating systems. If I succeed I'll issue a new PR, else I will merge this one.

**Comment by guiv42** [comment]
superseded by #433

**Pull request closed without merging**
