### PR TITLE
Improve tuplet handling

### PR DESCRIPTION
**Pull request by Makoha**
Improvements related to issue #118

This should allow tuxguitar to handle tuplets a lot better.
Please note that because the value of `TGDuration.QUARTER_TIME` is 960, tuxguitar is not able to compute precise durations for 7, 9, 11 and 13 tuplets. Idealy `TGDuration.QUARTER_TIME` should be set to 2882880 in order for tuxguitar to compute precise durations for all these tuplets, but simply changing `TGDuration.QUARTER_TIME` currently has some unintended consequences that would need to be handled first.
Because of this precision lose I have also added some patches that would fix some basic rounding errors when `TGDuration.QUARTER_TIME` is 960.

I am new to GitHub and contributing to open source projects, so constructive criticism is appreciated.

### CODE REVIEW

**Comment by guiv42** [comment]
Thanks for the PR. I'll try to have a look, but this tuplet handling feature is not so trivial to me. (And this might take some time)
I already faced some difficulties when trying to improve tuplets representation (7e5e373241c41b066a8b0ec7cc05c34984c4c45b). In this case I tried to measure beats duration using an integer number of the shortest possible note, to avoid rounding effects.

**Comment by Makoha** [comment]
No problem. These rounding errors are tricky to deal with, which is why I strongly would recommend working towards setting `TGDuration.QUARTER_TIME` to 2882880. (Or maybe even bigger to handle larger tuplets?)
My goal with this commit was to improve upon current functionality without breaking things.
Working on this, I believe I have gotten a fairly good understanding how durations are handled, so please ask if you have any questions.

**Comment by guiv42** [comment]
> My goal with this commit was to improve upon current functionality without breaking things.

Understood. And thank you for this! (it's the same strategy I'm trying to apply since this fork started here)

I agree that a "correct" cleanup would require to modify this 960 value. But I admit it's quite difficult to evaluate all possible consequences.

**Review by guiv42 — APPROVED** [review]
Thanks a lot, good job!

**Pull request merged**
