### PR TITLE
Fix for issue #31

### PR DESCRIPTION
**Pull request by guiv42**
when reading a conf file from an older TuxGuitar's version, not all parameters may be defined. Undefined parameters need to be set to their default values.

Before this fix, undefined parameters led to null TGProperties objects 

see #31

### CODE REVIEW

**Comment by helge17** [comment]
With the version number in the name of the config folder, all user settings were gone every time TuxGuitar was updated. By deleting the version number I wanted the users to keep their settings after an update.

But I have to admit that I didn't test what happens when new settings are added.

Your patch takes into account new entries in tuxguitar.cfg, but I'm not sure if it also reads new entries from tuxguitar-plugin-settings.cfg. Shouldn't this file be taken into account as well?

Sorry for the extra work... I can also put the version number back into the config folder name, then TuxGuitar would at least behave like version 1.5.6.

**Comment by guiv42** [comment]
I'm perfectly OK with this removal of version number in folder name. I've read a bit on SF the history of this patch, it's clear that successive versions somehow polluted the users' home folder. So no problem about that, we just have to do it properly.
Thank you for completing the analysis: I have not tried for plugin settings config file, essentially because I don't know what it's used for. No idea if my patch would handle this case also...
If you know one feature which is using some of these parameters it should be quite easy to test: just edit the config file, remove manually a few lines, start TuxGuitar and play with this feature (see the example in #31 with color.play.note and settings dialog). It may or may not raise an exception, depending from each feature implementation...
Tell me if you can identify such a scenario, I could test and debug if needed.

**Comment by helge17** [comment]
I made the following tests with TuxGuitar including this patch:

1. rm -rf ~/.config/tuxguitar && tuxguitar &
2. Look at Tools - Plugins and verify:
   Debug Helper Plugin:              disabled
   TuxGuitar Community Integration:  disabled
   Java Sound Api Plugin:            enabled
3. Close Dialog and exit TuxGuitar without changing any setting.
  ~/.config/tuxguitar/config/tuxguitar-plugin-settings.cfg contains the default settings:
  tuxguitar-community.enabled=false       # OK, as observed above
  tuxguitar-jsa.enabled=true              # OK, as observed above
  tuxguitar-fluidsynth.enabled=false
  tuxguitar-debug-helper.enabled=false    # OK, as observed above
  tuxguitar-jack.enabled=false
  tuxguitar-synth-export.enabled=true
  tuxguitar-gervill.enabled=false
  tuxguitar-alsa.enabled=false
4. Remove the three lines from the file. The other setting remain:
   tuxguitar-fluidsynth.enabled=false
   tuxguitar-jack.enabled=false
   tuxguitar-synth-export.enabled=true
   tuxguitar-gervill.enabled=false
   tuxguitar-alsa.enabled=false
5. tuxguitar &
6. Look at Tools - Plugins and verify:
   Debug Helper Plugin:              enabled    # not the default setting
   TuxGuitar Community Integration:  enabled    # not the default setting
   Java Sound Api Plugin:            enabled    # default setting, OK
7. Close Dialog and exit TuxGuitar without changing any setting.
8. ~/.config/tuxguitar/config/tuxguitar-plugin-settings.cfg still the same as in 4.
9. cat /dev/null > ~/.config/tuxguitar/config/tuxguitar-plugin-settings.cfg
10. Tools - Plugins: All plugins enabled

=> If a new plugin is added it is always enabled, even if it should be disabled according to /opt/tuxguitar/dist/tuxguitar-plugin-settings.cfg .

But this case is very rare, and TuxGuitar does not crash. So I think it is better to keep the version number out of the config folder name and add your patch.

**Comment by guiv42** [comment]
Thanks for this detailed tests!

**Pull request merged**
