### PR TITLE
fix compilation issue

### PR DESCRIPTION
**Pull request by guiv42**
see #110

### CODE REVIEW

**Comment by harborsiem** [comment]
@guiv42 You have done it correctly. I had forgotten the statement
```
private TGMeasureHeader readMeasureHeader(int number,TGSong song,TGTimeSignature timeSignature) throws IOException {
int index = number - 1;
...
```
The attached file may be helpful for format information inside *.gpx files
[GP4formatKorr.pdf](https://github.com/helge17/tuxguitar/files/12705867/GP4formatKorr.pdf)

**Comment by guiv42** [comment]
Thank you @harborsiem for the contribution. Looking at the initial issue description, I would have most probably focused on gp5, forgetting the other gp4,gp3, etc... Next time I will pull your repo to test it instead of just reading the commit. I'm still a beginner in git, and I don't really know how to work with several upstream repos.
Thanks also for the doc, I will have a look at it for the pinch harmonic issue also mentioned in #109 . Or maybe you want to do it yourself?

**Comment by harborsiem** [comment]
@guiv42 : I have no solution for the pinch harmonic issue.

**Comment by guiv42** [comment]
OK, I will have a look then

**Pull request merged**
