### PR TITLE
Fix French translation in tuxguitar.desktop

### PR DESCRIPTION
**Pull request by trebmuh**
HTH

### CODE REVIEW

**Comment by guiv42** [comment]
Thanks!
(je l'avais loupé celui-là)

just for information: some more translation work coming soon. All instruments names will be translatable soon, and I could not find all translations for percussion instruments in French...

**Comment by trebmuh** [comment]
Feel free to ping me then.
I'll be happy to offer translation if I've got time to do so by then.

**Comment by guiv42** [comment]
Thanks for your proposal. If you can have a look, names of percussions can now be translated (since f08f4fdcb2c04240615b9465d51b084f47876a69).
Translation files are here: [English version](https://github.com/helge17/tuxguitar/blob/master/desktop/TuxGuitar/share/lang/messages.properties), [French version](https://github.com/helge17/tuxguitar/blob/master/desktop/TuxGuitar/share/lang/messages_fr.properties), see the very end of the files.
I started already, looking for help in [wikipedia](https://fr.wikipedia.org/wiki/General_MIDI), but some names still puzzle me.
E.g. according to wikipedia article, "short/long whistle" translates to "sifflet aigu/grave", that sounds weird to me.
Also, I'm not sure about the different toms, I need some help from a drummer or percussionist!
- 41 "low floor" -> "basse grave"
- 43 "high floor" -> "basse aigu"
- 45 "low" -> "médium 4"
- 47 "low-mid" -> "médium 3"
- 48 "high-mid" -> "médium 2"
- 50 "high" -> "aigu"

**Comment by trebmuh** [comment]
@guiv42 : found time to update the French translation.
Still a few strings that I'm not sure how to translate, but I've updated most of the untranslated yet strings.
I've been doing a review for a few already-translated strings during the same time.
Hope that helps.

PS: I'm a drummer (and use to be a drum teacher for 10 years).

**Pull request merged**
